name: Build & Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: | 
          ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t cats-app .

      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY_SANDBOX }}" \
            -H "Accept: application/json" \
            https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}
